### ISSUE TITLE
Trying to make it even better.

### ISSUE THREAD

**Issue by oswaldoludwig** [cjratcliff/notes#1]
Thanks for this note! The text "Using NCE rather than a more traditional method means modelling p(C=1|w, c) rather than p(c|w)" made everything instantly clear to me, please make sure wheter it's p(c|w) or p(w|c). I would also remove the text "the sigmoid function transforms it into a probability", it helps in understanding, but isn't correct, being within the interval [0, 1] doesn't define probability by itself.

**Comment by cjratcliff** [comment]
Thanks! I've recently been making efforts to replace this wiki with an improved version using readthedocs. I've made some changes/additions to the NCE definition on there (https://ml-compiled.readthedocs.io/en/latest/loss_functions.html#noise-contrastive-estimation) to reflect your suggestions. As well as fixing the wording about the sigmoid I made it a bit more generic since NCE is useful outside of language modelling too.
